app = "spotifi"

primary_region = "sin" # singapore 

[env]
  PORT = "8001"

[build]
  dockerfile = "./Dockerfile"

[[services]]
  internal_port = 8001
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    path = "/"
    interval = 10000
    timeout = 2000
